export enum IpcChannel {
  // Branch operations
  GET_BRANCHES = 'db:get-branches',
  GET_BRANCH = 'db:get-branch',
  GET_BRANCH_BY_CODE = 'db:get-branch-by-code',
  GET_ACTIVE_BRANCHES = 'db:get-active-branches',
  CREATE_BRANCH = 'db:create-branch',
  UPDATE_BRANCH = 'db:update-branch',
  DELETE_BRANCH = 'db:delete-branch',

  // Category operations
  GET_CATEGORIES = 'db:get-categories',
  GET_CATEGORIES_PAGINATED = 'db:get-categories-paginated',
  GET_CATEGORY = 'db:get-category',
  GET_CATEGORY_BY_CODE = 'db:get-category-by-code',
  GET_CATEGORIES_BY_TYPE = 'db:get-categories-by-type',
  GET_ROOT_CATEGORIES = 'db:get-root-categories',
  CREATE_CATEGORY = 'db:create-category',
  UPDATE_CATEGORY = 'db:update-category',
  DELETE_CATEGORY = 'db:delete-category',

  // Client operations
  GET_CLIENTS = 'db:get-clients',
  GET_CLIENTS_PAGINATED = 'db:get-clients-paginated',
  GET_CLIENT = 'db:get-client',
  GET_CLIENT_BY_EMAIL = 'db:get-client-by-email',
  SEARCH_CLIENTS = 'db:search-clients',
  SEARCH_CLIENTS_FOR_SELECT = 'db:search-clients-for-select',
  CREATE_CLIENT = 'db:create-client',
  UPDATE_CLIENT = 'db:update-client',
  DELETE_CLIENT = 'db:delete-client',

  // Supplier operations
  GET_SUPPLIERS = 'db:get-suppliers',
  GET_SUPPLIERS_PAGINATED = 'db:get-suppliers-paginated',
  GET_SUPPLIER = 'db:get-supplier',
  GET_SUPPLIER_BY_CODE = 'db:get-supplier-by-code',
  GET_ACTIVE_SUPPLIERS = 'db:get-active-suppliers',
  SEARCH_SUPPLIERS = 'db:search-suppliers',
  CREATE_SUPPLIER = 'db:create-supplier',
  UPDATE_SUPPLIER = 'db:update-supplier',
  DELETE_SUPPLIER = 'db:delete-supplier',

  // Employee operations
  GET_EMPLOYEES = 'db:get-employees',
  GET_EMPLOYEES_PAGINATED = 'db:get-employees-paginated',
  GET_EMPLOYEE = 'db:get-employee',
  GET_EMPLOYEE_BY_USERNAME = 'db:get-employee-by-username',
  GET_EMPLOYEE_BY_CODE = 'db:get-employee-by-code',
  GET_ACTIVE_EMPLOYEES = 'db:get-active-employees',
  GET_SALESPEOPLE = 'db:get-salespeople',
  SEARCH_EMPLOYEES = 'db:search-employees',
  SEARCH_EMPLOYEES_FOR_SELECT = 'db:search-employees-for-select',
  CREATE_EMPLOYEE = 'db:create-employee',
  UPDATE_EMPLOYEE = 'db:update-employee',
  DELETE_EMPLOYEE = 'db:delete-employee',
  GENERATE_EMPLOYEE_CODE = 'db:generate-employee-code',
  AUTHENTICATE_EMPLOYEE = 'db:authenticate-employee',
  VERIFY_EMPLOYEE_PIN = 'db:verify-employee-pin',
  UPDATE_EMPLOYEE_PASSWORD = 'db:update-employee-password',
  UPDATE_EMPLOYEE_PERMISSIONS = 'db:update-employee-permissions',

  // Employee activity queries
  GET_EMPLOYEE_INVOICES = 'db:get-employee-invoices',
  GET_EMPLOYEE_QUOTATIONS = 'db:get-employee-quotations',
  GET_EMPLOYEE_CREDIT_NOTES = 'db:get-employee-credit-notes',
  GET_EMPLOYEE_PAYMENTS = 'db:get-employee-payments',
  GET_EMPLOYEE_ATTENDANCE = 'db:get-employee-attendance',
  GET_EMPLOYEE_ACTIVITY_SUMMARY = 'db:get-employee-activity-summary',

  // Inventory operations
  GET_INVENTORY = 'db:get-inventory',
  GET_INVENTORY_PAGINATED = 'db:get-inventory-paginated',
  GET_INVENTORY_ITEM = 'db:get-inventory-item',
  GET_INVENTORY_BY_SKU = 'db:get-inventory-by-sku',
  GET_LOW_STOCK_INVENTORY = 'db:get-low-stock-inventory',
  GET_ACTIVE_INVENTORY = 'db:get-active-inventory',
  SEARCH_INVENTORY = 'db:search-inventory',
  SEARCH_INVENTORY_FOR_SELECT = 'db:search-inventory-for-select',
  CREATE_INVENTORY = 'db:create-inventory',
  UPDATE_INVENTORY = 'db:update-inventory',
  DELETE_INVENTORY = 'db:delete-inventory',
  UPDATE_INVENTORY_STOCK = 'db:update-inventory-stock',

  // Variant operations
  GET_VARIANTS = 'db:get-variants',
  GET_VARIANTS_PAGINATED = 'db:get-variants-paginated',
  GET_VARIANT = 'db:get-variant',
  GET_VARIANTS_BY_INVENTORY = 'db:get-variants-by-inventory',
  GET_VARIANT_BY_BARCODE = 'db:get-variant-by-barcode',
  GET_VARIANT_BY_SKU = 'db:get-variant-by-sku',
  GET_ACTIVE_VARIANTS = 'db:get-active-variants',
  GET_LOW_STOCK_VARIANTS = 'db:get-low-stock-variants',
  SEARCH_VARIANTS_FOR_SELECT = 'db:search-variants-for-select',
  CREATE_VARIANT = 'db:create-variant',
  UPDATE_VARIANT = 'db:update-variant',
  DELETE_VARIANT = 'db:delete-variant',
  UPDATE_VARIANT_STOCK = 'db:update-variant-stock',
  SET_VARIANT_STOCK = 'db:set-variant-stock',

  // Invoice operations
  GET_INVOICES = 'db:get-invoices',
  GET_INVOICES_PAGINATED = 'db:get-invoices-paginated',
  GET_INVOICE = 'db:get-invoice',
  GET_INVOICE_BY_NUMBER = 'db:get-invoice-by-number',
  GET_INVOICES_BY_CLIENT = 'db:get-invoices-by-client',
  GET_INVOICES_BY_SALESPERSON = 'db:get-invoices-by-salesperson',
  GET_UNPAID_INVOICES = 'db:get-unpaid-invoices',
  GET_ADJACENT_INVOICES = 'db:get-adjacent-invoices',
  GET_ADJACENT_INVOICES_WITH_DATA = 'db:get-adjacent-invoices-with-data',
  CREATE_INVOICE = 'db:create-invoice',
  UPDATE_INVOICE = 'db:update-invoice',
  DELETE_INVOICE = 'db:delete-invoice',
  RECORD_INVOICE_PAYMENT = 'db:record-invoice-payment',
  ARCHIVE_INVOICE = 'db:archive-invoice',

  // Quotation operations
  GET_QUOTATIONS = 'db:get-quotations',
  GET_QUOTATIONS_PAGINATED = 'db:get-quotations-paginated',
  GET_QUOTATION = 'db:get-quotation',
  GET_QUOTATION_BY_NUMBER = 'db:get-quotation-by-number',
  GET_QUOTATIONS_BY_CLIENT = 'db:get-quotations-by-client',
  GET_QUOTATIONS_BY_SALESPERSON = 'db:get-quotations-by-salesperson',
  CREATE_QUOTATION = 'db:create-quotation',
  UPDATE_QUOTATION = 'db:update-quotation',
  DELETE_QUOTATION = 'db:delete-quotation',
  CONVERT_QUOTATION_TO_INVOICE = 'db:convert-quotation-to-invoice',
  EXPIRE_QUOTATION = 'db:expire-quotation',
  ARCHIVE_QUOTATION = 'db:archive-quotation',

  // Credit note operations
  GET_CREDIT_NOTES = 'db:get-credit-notes',
  GET_CREDIT_NOTES_PAGINATED = 'db:get-credit-notes-paginated',
  GET_CREDIT_NOTE = 'db:get-credit-note',
  GET_CREDIT_NOTE_BY_NUMBER = 'db:get-credit-note-by-number',
  GET_CREDIT_NOTES_BY_CLIENT = 'db:get-credit-notes-by-client',
  GET_CREDIT_NOTES_BY_INVOICE = 'db:get-credit-notes-by-invoice',
  GET_UNUSED_CREDIT_NOTES = 'db:get-unused-credit-notes',
  CREATE_CREDIT_NOTE = 'db:create-credit-note',
  UPDATE_CREDIT_NOTE = 'db:update-credit-note',
  DELETE_CREDIT_NOTE = 'db:delete-credit-note',
  RECORD_CREDIT_NOTE_USAGE = 'db:record-credit-note-usage',
  ARCHIVE_CREDIT_NOTE = 'db:archive-credit-note',

  // Document line item operations
  GET_DOCUMENT_LINE_ITEMS = 'db:get-document-line-items',
  GET_DOCUMENT_LINE_ITEMS_BY_INVOICE = 'db:get-document-line-items-by-invoice',
  GET_DOCUMENT_LINE_ITEMS_BY_QUOTATION = 'db:get-document-line-items-by-quotation',
  GET_DOCUMENT_LINE_ITEMS_BY_CREDIT_NOTE = 'db:get-document-line-items-by-credit-note',
  CREATE_DOCUMENT_LINE_ITEM = 'db:create-document-line-item',
  CREATE_DOCUMENT_LINE_ITEMS_BULK = 'db:create-document-line-items-bulk',
  UPDATE_DOCUMENT_LINE_ITEM = 'db:update-document-line-item',
  DELETE_DOCUMENT_LINE_ITEM = 'db:delete-document-line-item',
  DELETE_DOCUMENT_LINE_ITEMS_BY_DOCUMENT = 'db:delete-document-line-items-by-document',

  // Bill operations
  GET_BILLS = 'db:get-bills',
  GET_BILLS_PAGINATED = 'db:get-bills-paginated',
  GET_BILL = 'db:get-bill',
  GET_BILL_BY_NUMBER = 'db:get-bill-by-number',
  GET_BILLS_BY_SUPPLIER = 'db:get-bills-by-supplier',
  GET_UNPAID_BILLS = 'db:get-unpaid-bills',
  CREATE_BILL = 'db:create-bill',
  UPDATE_BILL = 'db:update-bill',
  DELETE_BILL = 'db:delete-bill',
  RECORD_BILL_PAYMENT = 'db:record-bill-payment',
  ARCHIVE_BILL = 'db:archive-bill',

  // Payment operations
  GET_PAYMENTS = 'db:get-payments',
  GET_PAYMENTS_PAGINATED = 'db:get-payments-paginated',
  GET_PAYMENT = 'db:get-payment',
  GET_PAYMENTS_BY_DOCUMENT_TYPE = 'db:get-payments-by-document-type',
  GET_PAYMENTS_BY_INVOICE = 'db:get-payments-by-invoice',
  GET_PAYMENTS_BY_CREDIT_NOTE = 'db:get-payments-by-credit-note',
  GET_PAYMENTS_BY_BILL = 'db:get-payments-by-bill',
  GET_PAYMENTS_BY_DATE_RANGE = 'db:get-payments-by-date-range',
  CREATE_PAYMENT = 'db:create-payment',
  CREATE_INVOICE_PAYMENT = 'db:create-invoice-payment',
  CREATE_BILL_PAYMENT = 'db:create-bill-payment',
  UPDATE_PAYMENT = 'db:update-payment',
  DELETE_PAYMENT = 'db:delete-payment',

  // Payment method operations
  GET_PAYMENT_METHODS = 'db:get-payment-methods',
  GET_PAYMENT_METHOD = 'db:get-payment-method',
  GET_PAYMENT_METHOD_BY_CODE = 'db:get-payment-method-by-code',
  GET_ACTIVE_PAYMENT_METHODS = 'db:get-active-payment-methods',
  CREATE_PAYMENT_METHOD = 'db:create-payment-method',
  UPDATE_PAYMENT_METHOD = 'db:update-payment-method',
  DELETE_PAYMENT_METHOD = 'db:delete-payment-method',

  // GCT payment operations
  GET_GCT_PAYMENTS = 'db:get-gct-payments',
  GET_GCT_PAYMENTS_PAGINATED = 'db:get-gct-payments-paginated',
  GET_GCT_PAYMENT = 'db:get-gct-payment',
  GET_GCT_PAYMENTS_BY_PERIOD = 'db:get-gct-payments-by-period',
  GET_GCT_PAYMENTS_BY_YEAR = 'db:get-gct-payments-by-year',
  CREATE_GCT_PAYMENT = 'db:create-gct-payment',
  UPDATE_GCT_PAYMENT = 'db:update-gct-payment',
  DELETE_GCT_PAYMENT = 'db:delete-gct-payment',

  // Employee attendance operations
  GET_ATTENDANCE = 'db:get-attendance',
  GET_ATTENDANCE_PAGINATED = 'db:get-attendance-paginated',
  GET_ATTENDANCE_RECORD = 'db:get-attendance-record',
  GET_ATTENDANCE_BY_EMPLOYEE = 'db:get-attendance-by-employee',
  GET_ATTENDANCE_BY_DATE_RANGE = 'db:get-attendance-by-date-range',
  GET_ACTIVE_CLOCK_IN = 'db:get-active-clock-in',
  CLOCK_IN = 'db:clock-in',
  CLOCK_OUT = 'db:clock-out',
  GET_TOTAL_HOURS = 'db:get-total-hours',
  CREATE_ATTENDANCE = 'db:create-attendance',
  UPDATE_ATTENDANCE = 'db:update-attendance',
  DELETE_ATTENDANCE = 'db:delete-attendance',

  // Inventory transaction operations
  GET_INVENTORY_TRANSACTIONS = 'db:get-inventory-transactions',
  GET_INVENTORY_TRANSACTIONS_PAGINATED = 'db:get-inventory-transactions-paginated',
  GET_INVENTORY_TRANSACTIONS_BY_SKU = 'db:get-inventory-transactions-by-sku',
  GET_INVENTORY_TRANSACTIONS_BY_DATE_RANGE = 'db:get-inventory-transactions-by-date-range',
  CREATE_INVENTORY_TRANSACTION = 'db:create-inventory-transaction',

  // Inventory alternates operations
  GET_INVENTORY_ALTERNATES = 'db:get-inventory-alternates',
  GET_INVENTORY_ALTERNATES_BY_PART = 'db:get-inventory-alternates-by-part',
  CREATE_INVENTORY_ALTERNATE = 'db:create-inventory-alternate',
  DELETE_INVENTORY_ALTERNATE = 'db:delete-inventory-alternate',

  // Inventory sales queries
  GET_VARIANT_SALES = 'db:get-variant-sales',
  GET_INVENTORY_SALES_SUMMARY = 'db:get-inventory-sales-summary',

  // Database configuration operations
  GET_DATABASE_CONFIG = 'db:get-config',
  UPDATE_DATABASE_CONFIG = 'db:update-config',
  TEST_DATABASE_CONNECTION = 'db:test-connection',
  RECONNECT_DATABASE = 'db:reconnect',
  CHECK_DATABASE_STATUS = 'db:check-status',
}
