export enum IpcChannel {
  // Branch operations
  GET_BRANCHES = 'db:get-branches',
  GET_BRANCH = 'db:get-branch',
  GET_BRANCH_BY_CODE = 'db:get-branch-by-code',
  GET_ACTIVE_BRANCHES = 'db:get-active-branches',
  CREATE_BRANCH = 'db:create-branch',
  UPDATE_BRANCH = 'db:update-branch',
  DELETE_BRANCH = 'db:delete-branch',

  // Category operations
  GET_CATEGORIES = 'db:get-categories',
  GET_CATEGORIES_PAGINATED = 'db:get-categories-paginated',
  GET_CATEGORY = 'db:get-category',
  GET_CATEGORY_BY_CODE = 'db:get-category-by-code',
  GET_CATEGORIES_BY_TYPE = 'db:get-categories-by-type',
  GET_ROOT_CATEGORIES = 'db:get-root-categories',
  CREATE_CATEGORY = 'db:create-category',
  UPDATE_CATEGORY = 'db:update-category',
  DELETE_CATEGORY = 'db:delete-category',

  // Client operations
  GET_CLIENTS = 'db:get-clients',
  GET_CLIENTS_PAGINATED = 'db:get-clients-paginated',
  GET_CLIENT = 'db:get-client',
  GET_CLIENT_BY_EMAIL = 'db:get-client-by-email',
  SEARCH_CLIENTS = 'db:search-clients',
  SEARCH_CLIENTS_FOR_SELECT = 'db:search-clients-for-select',
  CREATE_CLIENT = 'db:create-client',
  UPDATE_CLIENT = 'db:update-client',
  DELETE_CLIENT = 'db:delete-client',

  // Supplier operations
  GET_SUPPLIERS = 'db:get-suppliers',
  GET_SUPPLIERS_PAGINATED = 'db:get-suppliers-paginated',
  GET_SUPPLIER = 'db:get-supplier',
  GET_SUPPLIER_BY_CODE = 'db:get-supplier-by-code',
  GET_ACTIVE_SUPPLIERS = 'db:get-active-suppliers',
  SEARCH_SUPPLIERS = 'db:search-suppliers',
  SEARCH_SUPPLIERS_FOR_SELECT = 'db:search-suppliers-for-select',
  CREATE_SUPPLIER = 'db:create-supplier',
  UPDATE_SUPPLIER = 'db:update-supplier',
  DELETE_SUPPLIER = 'db:delete-supplier',
  ACTIVATE_SUPPLIER = 'db:activate-supplier',
  DEACTIVATE_SUPPLIER = 'db:deactivate-supplier',

  // Employee operations
  GET_EMPLOYEES = 'db:get-employees',
  GET_EMPLOYEES_PAGINATED = 'db:get-employees-paginated',
  GET_EMPLOYEE = 'db:get-employee',
  GET_EMPLOYEE_BY_USERNAME = 'db:get-employee-by-username',
  GET_EMPLOYEE_BY_CODE = 'db:get-employee-by-code',
  GET_ACTIVE_EMPLOYEES = 'db:get-active-employees',
  GET_SALESPEOPLE = 'db:get-salespeople',
  SEARCH_EMPLOYEES = 'db:search-employees',
  SEARCH_EMPLOYEES_FOR_SELECT = 'db:search-employees-for-select',
  CREATE_EMPLOYEE = 'db:create-employee',
  UPDATE_EMPLOYEE = 'db:update-employee',
  DELETE_EMPLOYEE = 'db:delete-employee',
  GENERATE_EMPLOYEE_CODE = 'db:generate-employee-code',
  AUTHENTICATE_EMPLOYEE = 'db:authenticate-employee',
  VERIFY_EMPLOYEE_PIN = 'db:verify-employee-pin',
  UPDATE_EMPLOYEE_PASSWORD = 'db:update-employee-password',
  UPDATE_EMPLOYEE_PERMISSIONS = 'db:update-employee-permissions',
  RESET_EMPLOYEE_ACCESS_CODE = 'db:reset-employee-access-code',

  // Employee activity queries
  GET_EMPLOYEE_INVOICES = 'db:get-employee-invoices',
  GET_EMPLOYEE_QUOTATIONS = 'db:get-employee-quotations',
  GET_EMPLOYEE_CREDIT_NOTES = 'db:get-employee-credit-notes',
  GET_EMPLOYEE_PAYMENTS = 'db:get-employee-payments',
  GET_EMPLOYEE_ATTENDANCE = 'db:get-employee-attendance',
  GET_EMPLOYEE_ACTIVITY_SUMMARY = 'db:get-employee-activity-summary',

  // Inventory operations
  GET_INVENTORY = 'db:get-inventory',
  GET_INVENTORY_PAGINATED = 'db:get-inventory-paginated',
  GET_INVENTORY_ITEM = 'db:get-inventory-item',
  GET_INVENTORY_BY_SKU = 'db:get-inventory-by-sku',
  GET_PART_LABELS_BY_SKUS = 'db:get-part-labels-by-skus',
  GET_LOW_STOCK_INVENTORY = 'db:get-low-stock-inventory',
  GET_ACTIVE_INVENTORY = 'db:get-active-inventory',
  SEARCH_INVENTORY = 'db:search-inventory',
  SEARCH_INVENTORY_FOR_SELECT = 'db:search-inventory-for-select',
  SEARCH_INVENTORY_WITH_VARIANTS = 'db:search-inventory-with-variants',
  GET_DISTINCT_CATEGORIES = 'db:get-distinct-categories',
  GET_DISTINCT_MODELS = 'db:get-distinct-models',
  GET_INVENTORY_VARIANTS = 'db:get-inventory-variants',
  CHECK_HAS_VARIANTS = 'db:check-has-variants',
  CREATE_INVENTORY = 'db:create-inventory',
  UPDATE_INVENTORY = 'db:update-inventory',
  DELETE_INVENTORY = 'db:delete-inventory',
  UPDATE_INVENTORY_STOCK = 'db:update-inventory-stock',

  // Variant operations
  GET_VARIANTS = 'db:get-variants',
  GET_VARIANTS_PAGINATED = 'db:get-variants-paginated',
  GET_VARIANT = 'db:get-variant',
  GET_VARIANTS_BY_INVENTORY = 'db:get-variants-by-inventory',
  GET_VARIANT_BY_BARCODE = 'db:get-variant-by-barcode',
  GET_VARIANT_BY_SKU = 'db:get-variant-by-sku',
  GET_ACTIVE_VARIANTS = 'db:get-active-variants',
  GET_LOW_STOCK_VARIANTS = 'db:get-low-stock-variants',
  SEARCH_VARIANTS_FOR_SELECT = 'db:search-variants-for-select',
  CREATE_VARIANT = 'db:create-variant',
  UPDATE_VARIANT = 'db:update-variant',
  DELETE_VARIANT = 'db:delete-variant',
  UPDATE_VARIANT_STOCK = 'db:update-variant-stock',
  SET_VARIANT_STOCK = 'db:set-variant-stock',

  // Invoice operations
  GET_INVOICES = 'db:get-invoices',
  GET_INVOICES_PAGINATED = 'db:get-invoices-paginated',
  GET_INVOICE = 'db:get-invoice',
  GET_INVOICE_BY_NUMBER = 'db:get-invoice-by-number',
  GET_INVOICES_BY_CLIENT = 'db:get-invoices-by-client',
  GET_INVOICES_BY_SALESPERSON = 'db:get-invoices-by-salesperson',
  GET_UNPAID_INVOICES = 'db:get-unpaid-invoices',
  GET_ADJACENT_INVOICES = 'db:get-adjacent-invoices',
  GET_ADJACENT_INVOICES_WITH_DATA = 'db:get-adjacent-invoices-with-data',
  CREATE_INVOICE = 'db:create-invoice',
  UPDATE_INVOICE = 'db:update-invoice',
  DELETE_INVOICE = 'db:delete-invoice',
  RECORD_INVOICE_PAYMENT = 'db:record-invoice-payment',
  ARCHIVE_INVOICE = 'db:archive-invoice',

  // Invoice status operations
  GET_RECENT_INVOICES = 'db:get-recent-invoices',
  GET_OVERDUE_INVOICES = 'db:get-overdue-invoices',
  SEARCH_INVOICES = 'db:search-invoices',
  CHECK_INVOICE_INVENTORY = 'db:check-invoice-inventory',
  ADJUST_STOCK_BY_SKU = 'db:adjust-stock-by-sku',
  CREATE_INVOICE_TRANSACTIONS = 'db:create-invoice-transactions',
  REISSUE_INVOICE_TRANSACTIONS = 'db:reissue-invoice-transactions',
  CREATE_INVOICE_WITH_PAYMENT = 'db:create-invoice-with-payment',

  // Spotlight search
  SPOTLIGHT_SEARCH = 'db:spotlight-search',

  // Access code verification
  VERIFY_ACCESS_CODE = 'db:verify-access-code',
  CHECK_SALESPERSON_ACCESS = 'db:check-salesperson-access',

  // Permission override audit (one-time elevated access grants)
  RECORD_ACCESS_OVERRIDE = 'db:record-access-override',
  GET_ACCESS_OVERRIDES = 'db:get-access-overrides',

  // RBAC role operations
  GET_ROLES = 'db:get-roles',
  GET_ROLE = 'db:get-role',
  CREATE_ROLE = 'db:create-role',
  UPDATE_ROLE = 'db:update-role',
  DELETE_ROLE = 'db:delete-role',
  ASSIGN_EMPLOYEE_ROLE = 'db:assign-employee-role',

  // Credit check operations
  CHECK_CLIENT_CREDIT = 'db:check-client-credit',
  GET_CLIENT_ARREARS_INFO = 'db:get-client-arrears-info',

  // Quotation operations
  GET_QUOTATIONS = 'db:get-quotations',
  GET_QUOTATIONS_PAGINATED = 'db:get-quotations-paginated',
  GET_QUOTATION = 'db:get-quotation',
  GET_QUOTATION_BY_NUMBER = 'db:get-quotation-by-number',
  GET_QUOTATIONS_BY_CLIENT = 'db:get-quotations-by-client',
  GET_QUOTATIONS_BY_SALESPERSON = 'db:get-quotations-by-salesperson',
  CREATE_QUOTATION = 'db:create-quotation',
  UPDATE_QUOTATION = 'db:update-quotation',
  DELETE_QUOTATION = 'db:delete-quotation',
  CONVERT_QUOTATION_TO_INVOICE = 'db:convert-quotation-to-invoice',
  EXPIRE_QUOTATION = 'db:expire-quotation',
  ARCHIVE_QUOTATION = 'db:archive-quotation',
  GET_ADJACENT_QUOTATIONS = 'db:get-adjacent-quotations',
  GET_RECENT_QUOTATIONS = 'db:get-recent-quotations',

  // Credit note operations
  GET_CREDIT_NOTES = 'db:get-credit-notes',
  GET_CREDIT_NOTES_PAGINATED = 'db:get-credit-notes-paginated',
  GET_CREDIT_NOTE = 'db:get-credit-note',
  GET_CREDIT_NOTE_BY_NUMBER = 'db:get-credit-note-by-number',
  GET_CREDIT_NOTES_BY_CLIENT = 'db:get-credit-notes-by-client',
  GET_CREDIT_NOTES_BY_INVOICE = 'db:get-credit-notes-by-invoice',
  GET_UNUSED_CREDIT_NOTES = 'db:get-unused-credit-notes',
  CREATE_CREDIT_NOTE = 'db:create-credit-note',
  UPDATE_CREDIT_NOTE = 'db:update-credit-note',
  DELETE_CREDIT_NOTE = 'db:delete-credit-note',
  RECORD_CREDIT_NOTE_USAGE = 'db:record-credit-note-usage',
  ARCHIVE_CREDIT_NOTE = 'db:archive-credit-note',
  RESTORE_CREDIT_NOTE_INVENTORY = 'db:restore-credit-note-inventory',
  PROCESS_INVOICE_RETURN = 'db:process-invoice-return',

  // Document line item operations
  GET_DOCUMENT_LINE_ITEMS = 'db:get-document-line-items',
  GET_DOCUMENT_LINE_ITEMS_BY_INVOICE = 'db:get-document-line-items-by-invoice',
  GET_DOCUMENT_LINE_ITEMS_BY_QUOTATION = 'db:get-document-line-items-by-quotation',
  GET_DOCUMENT_LINE_ITEMS_BY_CREDIT_NOTE = 'db:get-document-line-items-by-credit-note',
  CREATE_DOCUMENT_LINE_ITEM = 'db:create-document-line-item',
  CREATE_DOCUMENT_LINE_ITEMS_BULK = 'db:create-document-line-items-bulk',
  UPDATE_DOCUMENT_LINE_ITEM = 'db:update-document-line-item',
  DELETE_DOCUMENT_LINE_ITEM = 'db:delete-document-line-item',
  DELETE_DOCUMENT_LINE_ITEMS_BY_DOCUMENT = 'db:delete-document-line-items-by-document',

  // Bill operations
  GET_BILLS = 'db:get-bills',
  GET_BILLS_PAGINATED = 'db:get-bills-paginated',
  GET_BILL = 'db:get-bill',
  GET_BILL_BY_NUMBER = 'db:get-bill-by-number',
  GET_BILLS_BY_SUPPLIER = 'db:get-bills-by-supplier',
  GET_UNPAID_BILLS = 'db:get-unpaid-bills',
  CREATE_BILL = 'db:create-bill',
  UPDATE_BILL = 'db:update-bill',
  DELETE_BILL = 'db:delete-bill',
  RECORD_BILL_PAYMENT = 'db:record-bill-payment',
  ARCHIVE_BILL = 'db:archive-bill',

  // Payment operations
  GET_PAYMENTS = 'db:get-payments',
  GET_PAYMENTS_PAGINATED = 'db:get-payments-paginated',
  GET_PAYMENT = 'db:get-payment',
  GET_PAYMENTS_BY_DOCUMENT_TYPE = 'db:get-payments-by-document-type',
  GET_PAYMENTS_BY_INVOICE = 'db:get-payments-by-invoice',
  GET_PAYMENTS_BY_CREDIT_NOTE = 'db:get-payments-by-credit-note',
  GET_PAYMENTS_BY_BILL = 'db:get-payments-by-bill',
  GET_PAYMENTS_BY_DATE_RANGE = 'db:get-payments-by-date-range',
  CREATE_PAYMENT = 'db:create-payment',
  CREATE_INVOICE_PAYMENT = 'db:create-invoice-payment',
  CREATE_BILL_PAYMENT = 'db:create-bill-payment',
  UPDATE_PAYMENT = 'db:update-payment',
  DELETE_PAYMENT = 'db:delete-payment',
  PROCESS_INVOICE_PAYMENT = 'db:process-invoice-payment',
  PROCESS_INVOICE_REFUND = 'db:process-invoice-refund',
  PROCESS_CLIENT_BULK_PAYMENT = 'db:process-client-bulk-payment',
  GET_CLIENT_OUTSTANDING_INVOICES = 'db:get-client-outstanding-invoices',
  VOID_PAYMENT = 'db:void-payment',
  GET_CLIENT_AVAILABLE_CREDIT_NOTES = 'db:get-client-available-credit-notes',

  // Payment method operations
  GET_PAYMENT_METHODS = 'db:get-payment-methods',
  GET_PAYMENT_METHOD = 'db:get-payment-method',
  GET_PAYMENT_METHOD_BY_CODE = 'db:get-payment-method-by-code',
  GET_ACTIVE_PAYMENT_METHODS = 'db:get-active-payment-methods',
  CREATE_PAYMENT_METHOD = 'db:create-payment-method',
  UPDATE_PAYMENT_METHOD = 'db:update-payment-method',
  DELETE_PAYMENT_METHOD = 'db:delete-payment-method',

  // GCT payment operations
  GET_GCT_PAYMENTS = 'db:get-gct-payments',
  GET_GCT_PAYMENTS_PAGINATED = 'db:get-gct-payments-paginated',
  GET_GCT_PAYMENT = 'db:get-gct-payment',
  GET_GCT_PAYMENTS_BY_PERIOD = 'db:get-gct-payments-by-period',
  GET_GCT_PAYMENTS_BY_YEAR = 'db:get-gct-payments-by-year',
  CREATE_GCT_PAYMENT = 'db:create-gct-payment',
  UPDATE_GCT_PAYMENT = 'db:update-gct-payment',
  DELETE_GCT_PAYMENT = 'db:delete-gct-payment',

  // Employee attendance operations
  GET_ATTENDANCE = 'db:get-attendance',
  GET_ATTENDANCE_PAGINATED = 'db:get-attendance-paginated',
  GET_ATTENDANCE_RECORD = 'db:get-attendance-record',
  GET_ATTENDANCE_BY_EMPLOYEE = 'db:get-attendance-by-employee',
  GET_ATTENDANCE_BY_DATE_RANGE = 'db:get-attendance-by-date-range',
  GET_ACTIVE_CLOCK_IN = 'db:get-active-clock-in',
  CLOCK_IN = 'db:clock-in',
  CLOCK_OUT = 'db:clock-out',
  GET_TOTAL_HOURS = 'db:get-total-hours',
  CREATE_ATTENDANCE = 'db:create-attendance',
  UPDATE_ATTENDANCE = 'db:update-attendance',
  DELETE_ATTENDANCE = 'db:delete-attendance',

  // Employee shifts operations (modern clock-in/out)
  GET_SHIFTS_BY_EMPLOYEE = 'db:get-shifts-by-employee',
  GET_SHIFTS_BY_DATE_RANGE = 'db:get-shifts-by-date-range',
  GET_ACTIVE_SHIFT = 'db:get-active-shift',
  CLOCK_IN_SHIFT = 'db:clock-in-shift',
  CLOCK_OUT_SHIFT = 'db:clock-out-shift',
  GET_TOTAL_SHIFT_HOURS = 'db:get-total-shift-hours',
  GET_SHIFT = 'db:get-shift',
  UPDATE_SHIFT = 'db:update-shift',
  DELETE_SHIFT = 'db:delete-shift',

  // Inventory transaction operations
  GET_INVENTORY_TRANSACTIONS = 'db:get-inventory-transactions',
  GET_INVENTORY_TRANSACTIONS_PAGINATED = 'db:get-inventory-transactions-paginated',
  GET_INVENTORY_TRANSACTIONS_BY_SKU = 'db:get-inventory-transactions-by-sku',
  GET_INVENTORY_TRANSACTIONS_BY_DATE_RANGE = 'db:get-inventory-transactions-by-date-range',
  CREATE_INVENTORY_TRANSACTION = 'db:create-inventory-transaction',

  // Inventory alternates operations
  GET_INVENTORY_ALTERNATES = 'db:get-inventory-alternates',
  GET_INVENTORY_ALTERNATES_BY_PART = 'db:get-inventory-alternates-by-part',
  CREATE_INVENTORY_ALTERNATE = 'db:create-inventory-alternate',
  DELETE_INVENTORY_ALTERNATE = 'db:delete-inventory-alternate',

  // Inventory receiving operations
  GET_INVENTORY_RECEIVING = 'db:get-inventory-receiving',
  GET_INVENTORY_RECEIVING_BY_ID = 'db:get-inventory-receiving-by-id',
  GET_INVENTORY_RECEIVING_BY_SKU = 'db:get-inventory-receiving-by-sku',
  GET_INVENTORY_RECEIVING_BY_SKU_PAGINATED = 'db:get-inventory-receiving-by-sku-paginated',
  GET_INVENTORY_RECEIVING_BY_SUPPLIER = 'db:get-inventory-receiving-by-supplier-paginated',
  GET_INVENTORY_RECEIVING_BY_SUPPLIER_ALL = 'db:get-inventory-receiving-by-supplier',
  CREATE_INVENTORY_RECEIVING = 'db:create-inventory-receiving',
  UPDATE_INVENTORY_RECEIVING = 'db:update-inventory-receiving',
  DELETE_INVENTORY_RECEIVING = 'db:delete-inventory-receiving',

  // Goods receiving module (atomic receival documents + import)
  POST_GOODS_RECEIVAL = 'db:post-goods-receival',
  GET_GOODS_RECEIVALS = 'db:get-goods-receivals',
  GET_GOODS_RECEIVAL_BY_ID = 'db:get-goods-receival-by-id',
  PARSE_RECEIVAL_IMPORT = 'db:parse-receival-import',

  // Inventory sales queries
  GET_VARIANT_SALES = 'db:get-variant-sales',
  GET_INVENTORY_SALES_SUMMARY = 'db:get-inventory-sales-summary',

  // Database configuration operations
  GET_DATABASE_CONFIG = 'db:get-config',
  UPDATE_DATABASE_CONFIG = 'db:update-config',
  TEST_DATABASE_CONNECTION = 'db:test-connection',
  RECONNECT_DATABASE = 'db:reconnect',
  CHECK_DATABASE_STATUS = 'db:check-status',
  RUN_MIGRATIONS_AND_SEEDS = 'db:run-migrations-and-seeds',

  // System settings operations
  GET_SYSTEM_SETTINGS = 'db:get-system-settings',
  GET_SYSTEM_SETTINGS_VISIBLE = 'db:get-system-settings-visible',
  GET_SYSTEM_SETTINGS_BY_GROUP = 'db:get-system-settings-by-group',
  GET_SYSTEM_SETTING = 'db:get-system-setting',
  GET_SYSTEM_SETTING_VALUE = 'db:get-system-setting-value',
  GET_TAX_RATE = 'db:get-tax-rate',
  SET_SYSTEM_SETTING = 'db:set-system-setting',
  UPSERT_SYSTEM_SETTING = 'db:upsert-system-setting',
  DELETE_SYSTEM_SETTING = 'db:delete-system-setting',
  INITIALIZE_SYSTEM_SETTINGS = 'db:initialize-system-settings',

  // File storage operations
  VALIDATE_STORAGE_PATH = 'db:validate-storage-path',
  REINITIALIZE_STORAGE = 'db:reinitialize-storage',
  GET_STORAGE_INFO = 'db:get-storage-info',

  // Inventory image operations
  UPLOAD_INVENTORY_IMAGE = 'db:upload-inventory-image',
  DELETE_INVENTORY_IMAGE = 'db:delete-inventory-image',
  GET_INVENTORY_IMAGES = 'db:get-inventory-images',
  GET_INVENTORY_IMAGES_WITH_DATA = 'db:get-inventory-images-with-data',
  GET_PRIMARY_THUMBNAIL = 'db:get-primary-thumbnail',
  GET_PRIMARY_THUMBNAILS_BATCH = 'db:get-primary-thumbnails-batch',
  SET_PRIMARY_IMAGE = 'db:set-primary-image',
  REORDER_IMAGES = 'db:reorder-images',
  GET_IMAGE_FILE = 'db:get-image-file',
  GET_ALL_PRODUCT_IMAGES = 'db:get-all-product-images',

  // Report operations
  GET_SALES_REPORT = 'db:get-sales-report',
  GET_RECEIVABLES_AGING_REPORT = 'db:get-receivables-aging-report',
  GET_PAYMENT_COLLECTION_REPORT = 'db:get-payment-collection-report',

  // Export operations
  EXPORT_REPORT = 'export:report',

  // Print operations
  PRINT_DOCUMENT = 'print:document',
  PRINT_DOCUMENT_PREVIEW = 'print:document-preview',
  PRINT_DOCUMENT_PDF = 'print:document-pdf',
  GET_AVAILABLE_PRINTERS = 'print:get-printers',
  GET_PRINT_SETTINGS = 'print:get-settings',
  PRINT_LOOKUP_TICKET = 'print:lookup-ticket',
  PRINT_RECEIVING_REFERENCE = 'print:receiving-reference',
  PRINT_CLIENT_STATEMENT = 'print:client-statement',
  PRINT_PAYMENT_REPORT = 'print:payment-report',
}
